name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build DB Initer App
        run: |
          make build-db-initer-app

      - name: Build Preparer App
        run: |
          make build-preparer-app

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: registry.goboolean.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push db-initer image to registry
        run: |
          docker tag fetch-system/util/db-initer:latest registry.goboolean.io/fetch-system/util/db-initer:${GITHUB_SHA::7}
          docker push registry.goboolean.io/fetch-system/util/db-initer:${GITHUB_SHA::7}

      - name: Push preparer image to registry
        run: |
          docker tag fetch-system/util/preparer:latest registry.goboolean.io/fetch-system/util/preparer:${GITHUB_SHA::7}
          docker push registry.goboolean.io/fetch-system/util/preparer:${GITHUB_SHA::7}

  kustomize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Extract image tag
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Update db-initer tag
        uses: goboolean/manifests/.github/actions/update-image-tag@main
        with:
          app-name: ${{ github.event.repository.name }}
          image-name: registry.goboolean.io/fetch-system/util/db-initer
          image-tag: ${{ env.SHORT_SHA }}
          github-token: ${{ secrets.GOBOOLEAN_IO_TOKEN }}
          profile: dev
          pull-request-link: ${{ github.event.pull_request.html_url }}

      - name: Update preparer tag
        uses: goboolean/manifests/.github/actions/update-image-tag@main
        with:
          app-name: ${{ github.event.repository.name }}
          image-name: registry.goboolean.io/fetch-system/util/preparer
          image-tag: ${{ env.SHORT_SHA }}
          github-token: ${{ secrets.GOBOOLEAN_IO_TOKEN }}
          profile: dev
          pull-request-link: ${{ github.event.pull_request.html_url }}
